# Ember Framework Configuration
# Basic configuration for model registry

# Model registry configuration
model_registry:
  # Whether to automatically discover models from provider APIs
  auto_discover: true
  
  # Whether to automatically register models from configuration
  auto_register: true
  
  # Provider configurations
  providers:
    # OpenAI configuration
    openai:
      enabled: true
      timeout: 30.0
      max_retries: 3
      base_url: "https://api.openai.com/v1"
      
      # API keys - these can also be set via environment variables
      api_keys:
        default:
          key: "${OPENAI_API_KEY}"
      
      # Models configuration
      models:
        - id: "gpt-4o"
          name: "GPT-4o"
          cost:
            input_cost_per_thousand: 5.0
            output_cost_per_thousand: 15.0
          rate_limit:
            tokens_per_minute: 100000
            requests_per_minute: 500
        
        - id: "gpt-3.5-turbo"
          name: "GPT-3.5 Turbo"
          cost:
            input_cost_per_thousand: 0.5
            output_cost_per_thousand: 1.5
          rate_limit:
            tokens_per_minute: 180000
            requests_per_minute: 600
    
    # Anthropic configuration
    anthropic:
      enabled: true
      timeout: 30.0
      max_retries: 3
      base_url: "https://api.anthropic.com/v1"
      
      # API keys - these can also be set via environment variables
      api_keys:
        default:
          key: "${ANTHROPIC_API_KEY}"
      
      # Models configuration
      models:
        - id: "claude-3-opus-20240229"
          name: "Claude 3 Opus"
          cost:
            input_cost_per_thousand: 15.0
            output_cost_per_thousand: 75.0
          rate_limit:
            tokens_per_minute: 50000
            requests_per_minute: 100
        
        - id: "claude-3-sonnet-20240229"
          name: "Claude 3 Sonnet"
          cost:
            input_cost_per_thousand: 3.0
            output_cost_per_thousand: 15.0
          rate_limit:
            tokens_per_minute: 80000
            requests_per_minute: 200

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"