[project]
name = "avior"
version = "0.1.0"
description = "Describe your project here"
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
dependencies = [
    "fastapi>=0.104.1",
    "pydantic>=2.5.2",
    "pydantic-settings>=2.1.0",
    "uvicorn>=0.24.0.post1",
    "requests>=2.31.0",
    "pytest>=8.3.3",
    "parameterized>=0.9.0",
]
requires-python = ">=3.11"
readme = "README.md"
license = {file = "LICENSE"}

[tool.pdm.build]
includes = ["src"]

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=8.3.3",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend" 