# Base configuration for model registry
registry:
  providers:
    - name: "OpenAI"
      api_key: "your-api-key-here"  # Replace with actual key
      models:
        - name: "gpt-4"
          cost:
            input: 0.03  # $ per 1k tokens
            output: 0.06  # $ per 1k tokens
    
    - name: "Anthropic"
      api_key: "your-api-key-here"  # Replace with actual key
      models:
        - name: "claude-2"
          cost:
            input: 0.02
            output: 0.05

  default_provider: "OpenAI"
  cache_enabled: true
  rate_limiting:
    enabled: true
    requests_per_minute: 100 